tmgmt.translator.settings.thebigword:
  type: tmgmt.translator_base
  mapping:
    client_contact_key:
      type: string
      label: Thebigword client contact key

tmgmt_thebigword.settings:
  type: config_object
  mapping:
    use_mock_service:
      type: boolean
      label: Use mock service
