tmgmt.translator.settings.thebigword:
  type: tmgmt.translator_base
  mapping:
    client_contact_key:
      type: string
      label: Thebigword client contact key

tmgmt_thebigword.settings:
  type: config_object
  mapping:
    service_url:
      type: string
      label: URL of thebigword translation service.
